for i in {1..10}
do
 	filebench -f workloads/fileserver_pmem_1nt_100knf.f
	filebench -f workloads/fileserver_pmem_1nt_800knf.f
	filebench -f workloads/fileserver_pmem_1nt_3.2mnf.f
	filebench -f workloads/fileserver_pmem_5nt_100knf.f
	filebench -f workloads/fileserver_pmem_5nt_800knf.f
	filebench -f workloads/fileserver_pmem_5nt_3.2mnf.f
	filebench -f workloads/fileserver_pmem_10nt_100knf.f
	filebench -f workloads/fileserver_pmem_10nt_800knf.f
	filebench -f workloads/fileserver_pmem_10nt_3.2mnf.f
	filebench -f workloads/fileserver_pmem_25nt_100knf.f
	filebench -f workloads/fileserver_pmem_25nt_800knf.f
	filebench -f workloads/fileserver_pmem_25nt_3.2mnf.f
	filebench -f workloads/fileserver_pmem_50nt_100knf.f
	filebench -f workloads/fileserver_pmem_50nt_800knf.f
	filebench -f workloads/fileserver_pmem_50nt_3.2mnf.f
	filebench -f workloads/fileserver_pmem_100nt_100knf.f
	filebench -f workloads/fileserver_pmem_100nt_800knf.f
	filebench -f workloads/fileserver_pmem_100nt_3.2mnf.f
	filebench -f workloads/varmail_pmem_1nt_100knf.f
	filebench -f workloads/varmail_pmem_1nt_800knf.f
	filebench -f workloads/varmail_pmem_1nt_8mnf.f
	filebench -f workloads/varmail_pmem_5nt_100knf.f
	filebench -f workloads/varmail_pmem_5nt_800knf.f
	filebench -f workloads/varmail_pmem_5nt_8mnf.f
	filebench -f workloads/varmail_pmem_10nt_100knf.f
	filebench -f workloads/varmail_pmem_10nt_800knf.f
	filebench -f workloads/varmail_pmem_10nt_8mnf.f
	filebench -f workloads/varmail_pmem_25nt_100knf.f
	filebench -f workloads/varmail_pmem_25nt_800knf.f
	filebench -f workloads/varmail_pmem_25nt_8mnf.f
	filebench -f workloads/varmail_pmem_50nt_100knf.f
	filebench -f workloads/varmail_pmem_50nt_800knf.f
	filebench -f workloads/varmail_pmem_50nt_8mnf.f
	filebench -f workloads/varmail_pmem_100nt_100knf.f
	filebench -f workloads/varmail_pmem_100nt_800knf.f
	filebench -f workloads/varmail_pmem_100nt_8mnf.f
	filebench -f workloads/webproxy_pmem_1nt_100knf.f
	filebench -f workloads/webproxy_pmem_1nt_800knf.f
	filebench -f workloads/webproxy_pmem_1nt_8mnf.f
	filebench -f workloads/webproxy_pmem_5nt_100knf.f
	filebench -f workloads/webproxy_pmem_5nt_800knf.f
	filebench -f workloads/webproxy_pmem_5nt_8mnf.f
	filebench -f workloads/webproxy_pmem_10nt_100knf.f
	filebench -f workloads/webproxy_pmem_10nt_800knf.f
	filebench -f workloads/webproxy_pmem_10nt_8mnf.f
	filebench -f workloads/webproxy_pmem_25nt_100knf.f
	filebench -f workloads/webproxy_pmem_25nt_800knf.f
	filebench -f workloads/webproxy_pmem_25nt_8mnf.f
	filebench -f workloads/webproxy_pmem_50nt_100knf.f
	filebench -f workloads/webproxy_pmem_50nt_800knf.f
	filebench -f workloads/webproxy_pmem_50nt_8mnf.f
	filebench -f workloads/webproxy_pmem_100nt_100knf.f
	filebench -f workloads/webproxy_pmem_100nt_800knf.f
	filebench -f workloads/webproxy_pmem_100nt_8mnf.f
	filebench -f workloads/webserver_pmem_1nt_100knf.f
	filebench -f workloads/webserver_pmem_1nt_800knf.f
	filebench -f workloads/webserver_pmem_1nt_4mnf.f
	filebench -f workloads/webserver_pmem_5nt_100knf.f
	filebench -f workloads/webserver_pmem_5nt_800knf.f
	filebench -f workloads/webserver_pmem_5nt_4mnf.f
	filebench -f workloads/webserver_pmem_10nt_100knf.f
	filebench -f workloads/webserver_pmem_10nt_800knf.f
	filebench -f workloads/webserver_pmem_10nt_4mnf.f
	filebench -f workloads/webserver_pmem_25nt_100knf.f
	filebench -f workloads/webserver_pmem_25nt_800knf.f
	filebench -f workloads/webserver_pmem_25nt_4mnf.f
	filebench -f workloads/webserver_pmem_50nt_100knf.f
	filebench -f workloads/webserver_pmem_50nt_800knf.f
	filebench -f workloads/webserver_pmem_50nt_4mnf.f
	filebench -f workloads/webserver_pmem_100nt_100knf.f
	filebench -f workloads/webserver_pmem_100nt_800knf.f
	filebench -f workloads/webserver_pmem_100nt_4mnf.f
 done