for i in {1..10}
do
 	filebench -f workloads/fileserver_pmem_1nt_100knf.f > results/fileserver_pmem_1nt_100knf.f_${i}.result
	filebench -f workloads/fileserver_pmem_1nt_800knf.f > results/fileserver_pmem_1nt_800knf.f_${i}.result
	filebench -f workloads/fileserver_pmem_1nt_3200knf.f > results/fileserver_pmem_1nt_3200knf.f_${i}.result
	filebench -f workloads/fileserver_pmem_5nt_100knf.f > results/fileserver_pmem_5nt_100knf.f_${i}.result
	filebench -f workloads/fileserver_pmem_5nt_800knf.f > results/fileserver_pmem_5nt_800knf.f_${i}.result
	filebench -f workloads/fileserver_pmem_5nt_3200knf.f > results/fileserver_pmem_5nt_3200knf.f_${i}.result
	filebench -f workloads/fileserver_pmem_10nt_100knf.f > results/fileserver_pmem_10nt_100knf.f_${i}.result
	filebench -f workloads/fileserver_pmem_10nt_800knf.f > results/fileserver_pmem_10nt_800knf.f_${i}.result
	filebench -f workloads/fileserver_pmem_10nt_3200knf.f > results/fileserver_pmem_10nt_3200knf.f_${i}.result
	filebench -f workloads/fileserver_pmem_25nt_100knf.f > results/fileserver_pmem_25nt_100knf.f_${i}.result
	filebench -f workloads/fileserver_pmem_25nt_800knf.f > results/fileserver_pmem_25nt_800knf.f_${i}.result
	filebench -f workloads/fileserver_pmem_25nt_3200knf.f > results/fileserver_pmem_25nt_3200knf.f_${i}.result
	filebench -f workloads/fileserver_pmem_50nt_100knf.f > results/fileserver_pmem_50nt_100knf.f_${i}.result
	filebench -f workloads/fileserver_pmem_50nt_800knf.f > results/fileserver_pmem_50nt_800knf.f_${i}.result
	filebench -f workloads/fileserver_pmem_50nt_3200knf.f > results/fileserver_pmem_50nt_3200knf.f_${i}.result
	filebench -f workloads/fileserver_pmem_100nt_100knf.f > results/fileserver_pmem_100nt_100knf.f_${i}.result
	filebench -f workloads/fileserver_pmem_100nt_800knf.f > results/fileserver_pmem_100nt_800knf.f_${i}.result
	filebench -f workloads/fileserver_pmem_100nt_3200knf.f > results/fileserver_pmem_100nt_3200knf.f_${i}.result
	filebench -f workloads/varmail_pmem_1nt_100knf.f > results/varmail_pmem_1nt_100knf.f_${i}.result
	filebench -f workloads/varmail_pmem_1nt_800knf.f > results/varmail_pmem_1nt_800knf.f_${i}.result
	filebench -f workloads/varmail_pmem_1nt_8mnf.f > results/varmail_pmem_1nt_8mnf.f_${i}.result
	filebench -f workloads/varmail_pmem_5nt_100knf.f > results/varmail_pmem_5nt_100knf.f_${i}.result
	filebench -f workloads/varmail_pmem_5nt_800knf.f > results/varmail_pmem_5nt_800knf.f_${i}.result
	filebench -f workloads/varmail_pmem_5nt_8mnf.f > results/varmail_pmem_5nt_8mnf.f_${i}.result
	filebench -f workloads/varmail_pmem_10nt_100knf.f > results/varmail_pmem_10nt_100knf.f_${i}.result
	filebench -f workloads/varmail_pmem_10nt_800knf.f > results/varmail_pmem_10nt_800knf.f_${i}.result
	filebench -f workloads/varmail_pmem_10nt_8mnf.f > results/varmail_pmem_10nt_8mnf.f_${i}.result
	filebench -f workloads/varmail_pmem_25nt_100knf.f > results/varmail_pmem_25nt_100knf.f_${i}.result
	filebench -f workloads/varmail_pmem_25nt_800knf.f > results/varmail_pmem_25nt_800knf.f_${i}.result
	filebench -f workloads/varmail_pmem_25nt_8mnf.f > results/varmail_pmem_25nt_8mnf.f_${i}.result
	filebench -f workloads/varmail_pmem_50nt_100knf.f > results/varmail_pmem_50nt_100knf.f_${i}.result
	filebench -f workloads/varmail_pmem_50nt_800knf.f > results/varmail_pmem_50nt_800knf.f_${i}.result
	filebench -f workloads/varmail_pmem_50nt_8mnf.f > results/varmail_pmem_50nt_8mnf.f_${i}.result
	filebench -f workloads/varmail_pmem_100nt_100knf.f > results/varmail_pmem_100nt_100knf.f_${i}.result
	filebench -f workloads/varmail_pmem_100nt_800knf.f > results/varmail_pmem_100nt_800knf.f_${i}.result
	filebench -f workloads/varmail_pmem_100nt_8mnf.f > results/varmail_pmem_100nt_8mnf.f_${i}.result
	filebench -f workloads/webproxy_pmem_1nt_100knf.f > results/webproxy_pmem_1nt_100knf.f_${i}.result
	filebench -f workloads/webproxy_pmem_1nt_800knf.f > results/webproxy_pmem_1nt_800knf.f_${i}.result
	filebench -f workloads/webproxy_pmem_1nt_8mnf.f > results/webproxy_pmem_1nt_8mnf.f_${i}.result
	filebench -f workloads/webproxy_pmem_5nt_100knf.f > results/webproxy_pmem_5nt_100knf.f_${i}.result
	filebench -f workloads/webproxy_pmem_5nt_800knf.f > results/webproxy_pmem_5nt_800knf.f_${i}.result
	filebench -f workloads/webproxy_pmem_5nt_8mnf.f > results/webproxy_pmem_5nt_8mnf.f_${i}.result
	filebench -f workloads/webproxy_pmem_10nt_100knf.f > results/webproxy_pmem_10nt_100knf.f_${i}.result
	filebench -f workloads/webproxy_pmem_10nt_800knf.f > results/webproxy_pmem_10nt_800knf.f_${i}.result
	filebench -f workloads/webproxy_pmem_10nt_8mnf.f > results/webproxy_pmem_10nt_8mnf.f_${i}.result
	filebench -f workloads/webproxy_pmem_25nt_100knf.f > results/webproxy_pmem_25nt_100knf.f_${i}.result
	filebench -f workloads/webproxy_pmem_25nt_800knf.f > results/webproxy_pmem_25nt_800knf.f_${i}.result
	filebench -f workloads/webproxy_pmem_25nt_8mnf.f > results/webproxy_pmem_25nt_8mnf.f_${i}.result
	filebench -f workloads/webproxy_pmem_50nt_100knf.f > results/webproxy_pmem_50nt_100knf.f_${i}.result
	filebench -f workloads/webproxy_pmem_50nt_800knf.f > results/webproxy_pmem_50nt_800knf.f_${i}.result
	filebench -f workloads/webproxy_pmem_50nt_8mnf.f > results/webproxy_pmem_50nt_8mnf.f_${i}.result
	filebench -f workloads/webproxy_pmem_100nt_100knf.f > results/webproxy_pmem_100nt_100knf.f_${i}.result
	filebench -f workloads/webproxy_pmem_100nt_800knf.f > results/webproxy_pmem_100nt_800knf.f_${i}.result
	filebench -f workloads/webproxy_pmem_100nt_8mnf.f > results/webproxy_pmem_100nt_8mnf.f_${i}.result
	filebench -f workloads/webserver_pmem_1nt_100knf.f > results/webserver_pmem_1nt_100knf.f_${i}.result
	filebench -f workloads/webserver_pmem_1nt_800knf.f > results/webserver_pmem_1nt_800knf.f_${i}.result
	filebench -f workloads/webserver_pmem_1nt_4mnf.f > results/webserver_pmem_1nt_4mnf.f_${i}.result
	filebench -f workloads/webserver_pmem_5nt_100knf.f > results/webserver_pmem_5nt_100knf.f_${i}.result
	filebench -f workloads/webserver_pmem_5nt_800knf.f > results/webserver_pmem_5nt_800knf.f_${i}.result
	filebench -f workloads/webserver_pmem_5nt_4mnf.f > results/webserver_pmem_5nt_4mnf.f_${i}.result
	filebench -f workloads/webserver_pmem_10nt_100knf.f > results/webserver_pmem_10nt_100knf.f_${i}.result
	filebench -f workloads/webserver_pmem_10nt_800knf.f > results/webserver_pmem_10nt_800knf.f_${i}.result
	filebench -f workloads/webserver_pmem_10nt_4mnf.f > results/webserver_pmem_10nt_4mnf.f_${i}.result
	filebench -f workloads/webserver_pmem_25nt_100knf.f > results/webserver_pmem_25nt_100knf.f_${i}.result
	filebench -f workloads/webserver_pmem_25nt_800knf.f > results/webserver_pmem_25nt_800knf.f_${i}.result
	filebench -f workloads/webserver_pmem_25nt_4mnf.f > results/webserver_pmem_25nt_4mnf.f_${i}.result
	filebench -f workloads/webserver_pmem_50nt_100knf.f > results/webserver_pmem_50nt_100knf.f_${i}.result
	filebench -f workloads/webserver_pmem_50nt_800knf.f > results/webserver_pmem_50nt_800knf.f_${i}.result
	filebench -f workloads/webserver_pmem_50nt_4mnf.f > results/webserver_pmem_50nt_4mnf.f_${i}.result
	filebench -f workloads/webserver_pmem_100nt_100knf.f > results/webserver_pmem_100nt_100knf.f_${i}.result
	filebench -f workloads/webserver_pmem_100nt_800knf.f > results/webserver_pmem_100nt_800knf.f_${i}.result
	filebench -f workloads/webserver_pmem_100nt_4mnf.f > results/webserver_pmem_100nt_4mnf.f_${i}.result
 done


numactl -C 4-7 fio pmem.fio
